<?php
/**
 * @var \Bluz\View\View $this
 */
?>
<?php $uid = uniqid('form_', false); ?>
<form id="<?=$uid?>" action="<?=$this->url('media', 'crud')?>" class="form-horizontal" method="POST" enctype="multipart/form-data">
  <input type="hidden" name="_method" value="<?=$method?>"/>
  <input type="hidden" name="id" value="<?=$row->id?>"/>
  <div class="modal-content">
    <div class="modal-header">
      <h4 class="modal-title"><?= __('Media') ?></h4>
      <button type="button" class="close" data-dismiss="modal" aria-label="<?=__('Close')?>">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <div class="media">
        <div class="media-body">
          <div class="form-group row">
            <label class="col-form-label col-lg-2" for="name"><?=__('Title')?></label>
            <div class="col-lg-10">
              <input type="text" class="form-control" id="name" name="title" value="<?=($row->title)?>" required />
            </div>
          </div>
            <?php if ($method === 'POST') : ?>
              <div class="form-group row">
                <label class="col-form-label col-lg-2"><?=__('File')?></label>
                <div class="col-lg-10">
                  <input type="file" name="file" accept="image/*" required />
                </div>
              </div>
            <?php else: ?>
              <div class="form-group row">
                <label class="col-form-label col-lg-2"><?=__('File')?></label>
                <div class="col-lg-10">
                  <input type="text" class="form-control" readonly name="file" value="<?=($row->file)?>" />
                </div>
              </div>
              <div class="form-group row">
                <label class="col-form-label col-lg-2"><?=__('Type')?></label>
                <div class="col-lg-10">
                  <input type="text" class="form-control" readonly name="type" value="<?=($row->type)?>" />
                </div>
              </div>
              <div class="form-group row">
                <label class="col-form-label col-lg-2"><?=__('Link')?></label>
                <div class="col-lg-10">
                  <p class="form-control-static">
                    <a href="<?=$this->baseUrl($row->file)?>">
                        <?=\Bluz\Proxy\Router::getFullUrl().($row->file)?>
                    </a>
                  </p>
                </div>
              </div>
            <?php endif; ?>
        </div>
        <?php if (0 === strpos($row->type, 'image')) : ?>
        <a href="<?=$this->baseUrl($row->file)?>" class="thumbnail bluz-preview">
          <img src="<?=$this->baseUrl($row->thumb?:$row->file)?>" class="d-flex ml-3" alt="<?=$row->title?>" />
        </a>
        <?php endif; ?>
      </div>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary"><?=__('Save')?></button>
    </div>
  </div>
</form>
<?php
// need for plain request
if (isset($errors)) :
    $this->partial('crud/errors.phtml', ['uid' => $uid, 'errors' => $errors]);
endif;
?>