<?php
/**
 * @var \Bluz\Grid\Grid $grid
 */
if (!$grid) {
    return;
}
\Bluz\Proxy\Layout::headStyle('css/media.css');
?>
<script>
  // use data-spy="grid" for use AJAX for reload grid
  require(['bluz.grid']);
</script>
<div class="clearfix" data-spy="grid" data-grid="<?= $grid->getUid() ?>">

  <nav class="navbar navbar-light bg-light justify-content-between">
    <a href="<?= $this->url('media', 'crud') ?>" class="btn btn-primary navbar-btn"><?= __('Create') ?></a>
    <form action="<?= $this->url('media', 'grid') ?>" class="form-inline filter-form">
      <div class="input-group">
          <?php echo
          $this->partial(
              'grid/filter-search.phtml',
              [
                  'grid' => $grid,
                  'filters' => [
                      'title' => __('Title'),
                      'file' => __('File'),
                  ]
              ]
          )
          ?>
        <span class="input-group-btn">
          <button class="btn btn-secondary"><?= __("Search") ?></button>
        </span>
      </div>
    </form>
  </nav>
  <hr/>

  <?= $this->partial('grid/total.phtml', ['grid' => $grid]) ?>
  <?= $this->partial('grid/limit.phtml', ['grid' => $grid]) ?>
  <hr style="display: block; clear: both"/>
  <div class="card-deck">
    <?php foreach ($grid->getData() as $row) : ?>
    <div class="card mb-3">
      <a href="<?= $this->baseUrl($row['file']) ?>" data-ajax-preview>
        <img class="card-img-top" src="<?= $this->baseUrl($row['thumb']) ?>" alt="<?= esc($row['title']) ?>">
      </a>
      <div class="card-body">
        <div class="d-flex justify-content-end">
          <h4 class="card-title mr-auto p-2"><?= esc($row['title']) ?></h4>
          <a href="<?= $this->url('media', 'crud', ['id' => $row['id']]) ?>"
             class="btn btn-primary align-self-start mr-2"
             data-ajax-dialog data-ajax-method="get" data-modal-style="modal-lg">
            <i class="fa fa-pencil"></i>
          </a>
          <a href="<?= $this->url('media', 'crud', ['id' => $row['id']]) ?>"
             class="btn btn-danger align-self-start" data-confirm data-ajax data-ajax-method="delete">
            <i class="fa fa-trash-o"></i>
          </a>
        </div>
        <p class="card-text">
          <small class="text-muted">
            Uploaded by <a href="<?= $this->url('users', 'profile', ['id' => $row['userId']]) ?>"><?= $row['login'] ?></a>
            at <?= substr($row['created'], 0, -9) ?></small></p>
      </div>
    </div>
    <?php endforeach; ?>
  </div>
  <hr/>
  <?= $this->partial('grid/total.phtml', ['grid' => $grid]) ?>
  <?= $this->partial('grid/pagination.phtml', ['grid' => $grid]) ?>
</div>
