<?php
/**
 * @var \Bluz\View\View $this
 */
echo $this->style('css/media.css');
?>
<script>
  require(['bluz.media'], function(media) {
    media.load();
  });
</script>

<div class="modal-content">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <h4 class="modal-title"><?= __('Images') ?></h4>
  </div>
  <div id="media-upload" class="modal-body clearfix">
    <div class="row">
      <div class="col-lg-2">
        <div class="btn btn-success fileinput-button dz-clickable">
          <i class="glyphicon glyphicon-plus"></i>
          <span><?= __('Add files...') ?></span>
        </div></div>
      <div class="col-lg-8">
        <div id="media-progress" class="progress hide">
          <div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
        </div></div>
    </div>
    <div id="media-previews" class="media-grid drop-area clearfix">
      <div id="media-template" class="hidden">
        <div class="pull-left">
          <div class="panel panel-default">
            <div class="panel-heading">
              <div class="row">
                <div class="col-lg-8 text-overflow" data-dz-name></div>
                <div class="col-lg-4 text-right">
                  <a href="<?= $this->url('media', 'crud') ?>" class="confirm btn btn-xs btn-danger ajax"
                     data-ajax-method="delete">
                    <i class="fa fa-trash-o"></i>
                  </a>
                </div>
              </div>
            </div>
            <div class="panel-body text-center">
              <img data-dz-thumbnail />
            </div>
            <div class="panel-footer" data-dz-size></div>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>
