<?php
/**
 * @var \Bluz\View\View $this
 */
echo $this->style('css/media.css');
?>
<script>
  require(['bluz.media', 'jquery'], (media, $) => {
    window.media = media;
    media.load();
  });
  if (window.media !== undefined) {
    window.media.load();
  }
</script>

<div class="modal-content">
  <div class="modal-header">
    <h4 class="modal-title"><?= __('Images') ?></h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="<?=__('Close')?>">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div id="media-upload" class="modal-body">
    <div class="row">
      <div class="col-lg-2">
        <div class="btn btn-success fileinput-button dz-clickable">
          <i class="glyphicon glyphicon-plus"></i>
          <span><?= __('Add files...') ?></span>
        </div></div>
      <div class="col-lg-8">
        <div id="media-progress" class="progress" hidden>
          <div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
      </div>
    </div>
    <div id="media-previews" class="card-deck drop-area">
      <?php foreach ($images as $row) : ?>
        <div class="card mb-4" style="min-width: 240px; max-width: 240px"
             data-id="<?=$row['id']?>" data-thumb="<?=$row['thumb']?>" data-file="<?=$row['file']?>">
          <img class="card-img-top" src="<?= $this->baseUrl($row['thumb']) ?>" alt="<?= esc($row['title']) ?>">
          <div class="card-body">
            <div class="d-flex justify-content-end">
              <h4 class="card-title mr-auto p-2"><?= esc($row['title']) ?></h4>
              <a href="<?= $this->url('media', 'crud', ['id' => $row['id']]) ?>"
                 class="btn btn-xs btn-primary dialog align-self-start mr-2"
                 data-ajax-method="get" data-modal-style="modal-lg">
                <i class="fa fa-pencil"></i>
              </a>
              <a href="<?= $this->url('media', 'crud', ['id' => $row['id']]) ?>"
                 class="confirm btn btn-xs btn-danger ajax align-self-start" data-ajax-method="delete">
                <i class="fa fa-trash-o"></i>
              </a>
            </div>
            <p class="card-text"><small class="text-muted"><?=__('<strong>%d</strong> kb', ceil($row['size']/1024))?></small></p>
          </div>
        </div>
      <?php endforeach; ?>
    </div>
    <div id="media-template" hidden>
      <div class="card mb-4" style="min-width: 240px; max-width: 240px">
        <img class="card-img-top" src="" data-dz-thumbnail>
        <div class="card-body">
          <div class="d-flex justify-content-end">
            <h4 class="card-title mr-auto p-2" data-dz-name></h4>
            <a href="<?= $this->url('media', 'crud') ?>"
               class="btn btn-xs btn-primary dialog align-self-start mr-2"
               data-ajax-method="get" data-modal-style="modal-lg">
              <i class="fa fa-pencil"></i>
            </a>
            <a href="<?= $this->url('media', 'crud') ?>"
               class="confirm btn btn-xs btn-danger ajax align-self-start" data-ajax-method="delete">
              <i class="fa fa-trash-o"></i>
            </a>
          </div>
          <p class="card-text"><small class="text-muted" data-dz-size><?=__('<strong>%d</strong> kb', ceil($row['size']/1024))?></small></p>
        </div>
      </div>
    </div>
  </div>
</div>
